import { InstanceStatus, Regex } from '@companion-module/base'

export const EOL = '\r\n'
export const keep_alive_timeout = 30000
export const default_port = 23

export const cmd = {
	ping: 'W\\1002\\6001\\Pinging\\Chyron',
	changeColor: 'C',
	macro: 'E',
	changeFont: 'F',
	setDriveAndMessageDirectory: 'M',
	resendPrevious: 'Q',
	updateTabDataField: 'U',
	updateCurrentTemplate: 'U\\*',
	control: 'V',
	read: 'V\\5\\3\\1\\',
	readUpdateIntelligentInterface: 'V\\5\\13\\1\\',
	readUpdateExternalControl: 'V\\5\\14\\1\\',
	writeTabData: 'W',
	requestExternalUpdate: 'X', //Also R
	assorted: 'Y', //!!!
	eom: '\\\\',
	sep: '\\',
	pad: '0',
}

export const loginMsg = {
	welcome: 'Welcome to the ChyronHego Intelligent Interface Telnet Server on',
	inUse: 'already in use',
}

export const msgSuccess = '*'
export const errorCodes = [
	{ code: '00000001', label: 'Task timed out', status: InstanceStatus.UnknownError, loglevel: 'error' },
	{ code: '00000002', label: 'Unimplemented system service', status: InstanceStatus.UnknownError, loglevel: 'error' },
	{ code: '00000003', label: 'Illegal service', status: InstanceStatus.UnknownError, loglevel: 'error' },
	{ code: '00000004', label: 'Illegal node', status: InstanceStatus.UnknownError, loglevel: 'error' },
	{ code: '00000005', label: 'Object has been deleted', status: InstanceStatus.UnknownError, loglevel: 'error' },
	{ code: '00000006', label: 'Invalid object ID', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00000007', label: 'Incorrect object ID', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00000008', label: 'Incorrect object type', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00000009', label: 'Object not found', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00000014',
		label: 'Cannot create message - No task control blocks',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000015',
		label: 'Cannot create message - No stack space available',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000016',
		label: 'Cannot create the message -The stack space is too small',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000017',
		label: 'Cannot create the message -Priority out of range',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000018',
		label: 'Cannot start the process - Already active',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000019',
		label: 'Cannot restart the process - The process was never started',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000020',
		label: 'Cannot suspend process - Process is already suspended',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000021',
		label: 'Cannot resume process - It was never suspended',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000022',
		label: 'Cannot change priority - Out of range',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00000023', label: 'Illegal task register number', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00000024', label: 'Cannot delete - File is open', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00000051',
		label: 'Cannot create - No more queue control blocks',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000052',
		label: 'Cannot create or send - No message buffers',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000053',
		label: 'Cannot send - The message queue is full',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000054',
		label: 'Cannot receive - The queue has been deleted',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000055',
		label: 'Cannot receive - There are no pending messages',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000056',
		label: 'Informative - There were tasks waiting when the queue was deleted',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000057',
		label: 'Informative - There were messages waiting when the queue was deleted',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000066',
		label: 'Cannot acquire - Semaphore not available',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000067',
		label: 'Cannot acquire - Semaphore deleted while waiting',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00000068',
		label: 'Informative - There were tasks waiting when the Semaphore was deleted',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00002001',
		label: 'An invalid function number was called',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00002002', label: 'pHILE failure was encountered', status: InstanceStatus.UnknownError, loglevel: 'error' },
	{
		code: '00002003',
		label: 'An inconsistent structure was found on the volume',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00002005', label: 'Init volume parameter error', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002006', label: 'No more volume table entries', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002007', label: 'Alien volume', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002008', label: 'Volume already mounted', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00002009',
		label: 'Cannot unmount - there are files open',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '0000200A', label: 'Device not mounted', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000200B', label: 'File not found', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000200C', label: 'Illegal filename', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000200D', label: 'No Default Directory found', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000200E', label: 'Directory file expected', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000200F', label: 'Illegal annex size to create', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002010', label: 'Null filename', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002011', label: 'File already exists', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002012', label: 'F list full', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002013', label: 'File open', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002014', label: 'Directory is not empty', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002015', label: 'System or directory file', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002016', label: 'Different devices (MOVE_F)', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00002017',
		label: 'MOVE_F would result in non tree structure',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00002018', label: 'No more open file entries', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002019', label: 'No more FCBs', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000201A', label: 'Invalid FID, too large', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000201B', label: 'Invalid FID, file closed', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000201C', label: 'Indirect block full', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000201D', label: 'Volume full', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000201E', label: 'Bad position to lseek', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000201F', label: 'Seek past end of file', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00002021',
		label: 'Illegal device (exceeded maximum)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00002022', label: 'Data is locked', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002023', label: 'Bad fn in OPEN_VOL', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00002024',
		label: 'Illegal flush mode to MOUNT_VOL',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00002025', label: 'Illegal device name', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002026', label: 'Bad MS/DOS call', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002027', label: 'Illegal MS disk type', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00002028',
		label: 'More than one type of MS disk type',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00002040', label: 'Used Tab page', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002F01', label: 'Insufficient data area', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00002F0E', label: 'Check sum in pHILE', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000400B', label: 'Check sum in pVERIFY+', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '000040B2',
		label: 'Checksum does not match computed checksum',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000040B3',
		label: 'Requested message directory does not exist',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '0000412C',
		label: 'Requested message file does not exist',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '0000412D',
		label: 'Requested description file is not a Tab Description file',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '0000412E',
		label: 'Requested field is not a valid field',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '0000412F',
		label: 'Requested attribute (Color or Font) is not valid',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00004130',
		label: 'Field contains too much data (limit 64 characters)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00004131',
		label: 'Incorrect number of fields, R command does not match X command',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '0000415E',
		label: 'Description message was created with old Tabs (Templates)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '0000415F',
		label: 'Number of Tabs (Templates) exceeds limit (99)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00004190',
		label: 'Desired operation is not terminated with "\\\\"',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00004191',
		label: 'The command format is incorrect',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00004192',
		label: 'An invalid operation has been requested',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00004193',
		label: 'An invalid Machine ID has been used',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00004194',
		label: 'An invalid Effects ID has been used',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041C2',
		label: 'An invalid User ID has been used (either 1 or 2)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041C3',
		label: 'An invalid Keyboard ID has been used (either 1 or 2)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041C4',
		label: 'The command to set the active message compose frame buffer failed',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041C5',
		label: 'An invalid Frame Buffer ID was used (1, 2, or 3)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041C6',
		label:
			'Error building into a non-displaying buffer; a bad message type was used or no Read Next command was issued',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '000041C7', label: 'Command to set Palette failed', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '000041C8',
		label: 'Color Key out of range; must be 1 - 8',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041C9',
		label: 'Palette Index out of range; must be 1 - 31',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041CA',
		label: 'Color Index out of range; must be 0 - 255',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041CB',
		label: 'Key out of range; must be 0 - 1',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041CC',
		label: 'Attempted to perform a Dual-User operation in Single-User mode',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041CD',
		label: 'Timed out waiting for response',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041CE',
		label: 'Error building Message Compose Palette',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041CF',
		label: 'Error erasing displayed Frame Buffer',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041D0',
		label: 'Display/Non-Display flag out of range, i.e., 0 - 1',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '000041D1', label: 'No Intelligent Interface option', status: InstanceStatus.UnknownError, loglevel: 'warn' },
	{ code: '000041D2', label: 'Bitmap not created', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '000041D3', label: 'Bitmap file not found', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '000041D4', label: 'Invalid Field Number', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '000041D5', label: 'Missing Macro', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '000041D6', label: 'Macro Error', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '000041D7', label: 'Duplicate Macro', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '000041D8',
		label: 'Another Macro currently executing',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041D9',
		label: 'Another Macro currently recording',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041DA',
		label: 'Item referenced in Macro was not found',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '000041DB',
		label: 'File referenced in Macro was not found',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00005000', label: 'New Playlist created', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005001', label: 'Invalid Playlist Number', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005002', label: 'No Playlist loaded', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005003', label: 'File not Playlist', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005004', label: 'Old version of Playlist', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005005', label: 'Playlist already exists', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005006', label: 'Playlist finished executing', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005010', label: 'Invalid Playlist Entry Number', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00005011',
		label: 'Error allocating Playlist Entry',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00005012', label: 'Error adding Playlist Entry', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005020', label: 'Invalid Channel allocated', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005021', label: 'No Channel allocated', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005022', label: 'No Frame Buffer allocated', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005030', label: 'Invalid Still Message Number', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005031', label: 'Still File not found', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005050', label: 'Invalid IMAGESTOR! command', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005051', label: 'Invalid Effect', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005052', label: 'Invalid Pattern', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005053', label: 'Invalid Speed', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005054', label: 'Invalid Ease parameter', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005055', label: 'Invalid Reverse parameter', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00005056', label: 'Invalid Keyboard Lock Status', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00007000', label: 'No memory to create outline', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00007004',
		label: 'No Frame Buffer available for graph',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00007008',
		label: 'No memory for the Fill Line Buffer',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00007100',
		label: 'Line segment not between 0 and MAX_LINE_SEG',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00007108',
		label: 'Invalid Pulse parameter specified, i.e., not _PULSE(0) or _NON_PULSE(1)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '0000710C',
		label: 'Invalid display buffer specified, i.e., not _DBUF(0) or _NBUF(1)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00007110',
		label: 'Invalid Trigger type specified, i.e., not _REGULAR_LINE(0), _PULSE_LINE(1) or _BOTH(2)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00007114',
		label: 'Invalid Mode specified, i.e., not _ENTIRE_LINE(0) or _LAST_SEGMENT(1)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00007118',
		label: 'Specified Pacing value outside of range, i.e., not between -30 and 30',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00007200', label: 'Brush not successfully created', status: InstanceStatus.UnknownWarning },
	{
		code: '00007204',
		label: 'Invalid Edge specified, i.e., not _HARD(0), _SOFT(1), _SOFT_EDGE(2) or _CLEAR(3)',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '00007208',
		label: 'Invalid Transparency, i.e., not between 0 and 100',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '0000720C', label: 'Brush diameter out of range', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00007210',
		label: 'Invalid RGBA file name, i.e., RGBA value has more than 8 digits',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00007300', label: 'Point not added to outline', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00007304',
		label: 'No outline exists for this line segment',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00008001', label: 'Wrong Read Effect task', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00008002', label: 'Bad Read Effect command', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00008003', label: 'Wrong Read Effect command', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00008004', label: 'Bad Read Effect Mode', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00008005', label: 'Bad Read Effect Ease', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00008006', label: 'Bad Read Effect Speed', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00008007', label: 'Bad Read Effect Type', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00008008', label: 'Bad Read Effect Reverse', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00008009', label: 'Bad Read Effect Row Direction', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000800A', label: 'Bad Mix Effect Percent', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '0000800B', label: 'Bad Mix Effect Soft Edge', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '0000800C',
		label: 'Rows cannot be wiped left and right on old frame buffer',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{
		code: '0000800D',
		label: 'Must specify one row Up or Down',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '0000800E', label: 'Invalid Effect type', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '0000800F',
		label: 'No memory available for row type',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00008010', label: 'Frame buffer error occurred', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{
		code: '00008011',
		label: 'Frame buffer in use by another task, e.g., Clock, Flash',
		status: InstanceStatus.UnknownWarning,
		loglevel: 'warn',
	},
	{ code: '00805001', label: 'Bad Transform syntax', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00805002', label: 'Bad Transform script', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00805003', label: 'Bad Transform directory', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00805004', label: 'Bad Transform message', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00805005', label: 'Bad Transform value', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00805006', label: 'Ignored', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00805007', label: 'Bad Transform command', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
	{ code: '00805008', label: 'Transform not available', status: InstanceStatus.UnknownWarning, loglevel: 'warn' },
]

const textField = {
	type: 'textinput',
	useVariables: true,
	default: '',
	regex: Regex.SOMETHING,
}

const choices = {
	buffer: [
		{ id: '0', label: 'VGA' },
		{ id: '1', label: 'Frame Buffer 1' },
		{ id: '2', label: 'Frame Buffer 2' },
	],
	displayMode: [
		{ id: '0', label: 'Read Next (Prebuild)' },
		{ id: '1', label: 'Read & Display' },
	],
	readUpdate: [
		{ id: cmd.readUpdateIntelligentInterface, label: 'Read & Update All Intelligent Interface Fields' },
		{ id: cmd.readUpdateExternalControl, label: 'Read & Update External Update Fields' },
	],
}

export const actionOptions = {
	macro: {
		...textField,
		label: 'Macro',
		id: 'macro',
		tooltip: `Any VB Script command that can be executed via Lyric Macros may be contained in an E command.  Each command is separated by a "tilde" (~) character.`,
	},
	macroInfo: {
		type: 'static-text',
		id: 'info',
		label: 'Note the following about building macro subroutines using Intelligent Interface:',
		value: `The name of the macro subroutine that is built via Intelligent Interface cannot duplicate the name of any of the macros currently loaded in the Macros dialog box.  If there is a duplication, Intelligent Interface returns a 000041d7 (Duplicate Macro) error code. See below for A macro subroutine that is built via Intelligent Interface is not loaded into the Macros dialog box, and therefore does not appear in the dialog box. A macro subroutine that is successfully sent to Lyric can be overwritten, i.e., subsequent macros that are sent can have the same name.  The name restriction applies only to macros that are listed in the Macro dialog box. Additionally, if the macro engine is reset, the script must be resent. The E command can also trigger a loaded macro by executing its Hot Key.  Suppose that a macro script in Lyric is assigned the hot key trigger Alt + 3, meaning that it executes when Alt + 3 is pressed.  The following example uses a VB Script command to set up a shell object that passes commands to the Windows command interpreter.  A second VB Script command then sends the key combination Alt + 3, specified in VB Script as %3, triggering the macro script.E\\set WshShell = CreateObject ("WScript.Shell")~WshShell.SendKeys("%3")\\\\<CR><LF>`,
	},
	readBuffer: {
		id: 'buffer',
		label: 'Buffer',
		type: 'dropdown',
		choices: choices.buffer,
		default: choices.buffer[1].id,
		tooltip: 'Specifies destination of the message',
		allowCustom: false,
	},
	readMessage: {
		...textField,
		label: 'Lyric Message Number',
		id: 'message',
	},
	readDisplayMode: {
		id: 'mode',
		label: 'Display Mode',
		type: 'dropdown',
		choices: choices.displayMode,
		default: choices.displayMode[1].id,
	},
	readUpdate: {
		id: 'update',
		label: 'Update Mode',
		type: 'dropdown',
		choices: choices.readUpdate,
		default: choices.readUpdate[0].id,
	},
	customMessage: {
		...textField,
		label: 'Custom Message',
		id: 'message',
		tooltip: `Send custom message. Module will appead \\\\\\r\\n to the end.`,
	},
	templateDataMessage: {
		...textField,
		label: 'Template Data Message',
		id: 'templateDataMessage',
		tooltip: 'Variable should return an integer',
		default: '5501',
	},
	lyricMessage: {
		...textField,
		label: 'Lyric Message Number',
		id: 'lyricMessageNumber',
		tooltip: 'Variable should return an integer',
		default: '5500',
	},
	templateData: {
		...textField,
		label: 'Template Data',
		id: 'templates',
		tooltip: 'Can include multiple template fields seperated by \\',
		default: '',
	},
	templateNumber: {
		...textField,
		label: 'Template Number',
		id: 'templateNumber',
		tooltip: `The number that should be cited here is the field's specific identifying number as set in the Number control, and NOT a value representing the order in which the field was created. In other words, a command for Field 7 should be cite "7" and not the value "2", which specifies the order in which the fields were created.r`,
		default: '1',
	},
	templateInfo: {
		type: 'static-text',
		id: 'info',
		label: 'The following should be noted regarding W commands:',
		value: `A single-space update within a W command skips a 2D Text Template if and only if Auto-Erase is not enabled in the 2D Text Template dialog box.  The 2D Text Template dialog box is accessed by right-clicking on a 2D Text Template, then selecting Template Properties from the context-sensitive menu. A null update (\\\\) within a W command skips a 2D Text Template, regardless of Auto-Erase setting. If a W command attempts to overwrite a read-only file, an error is returned. When a Template Data Message created using the W command is read, Lyric displays the Message Number of the Template Description Message on the Canvas Title Bar. A Template Data Message can also be created by selectively recording (Ctrl + Record + D) the message from Lyric.`,
	},
	updateTemplateInfo: {
		type: 'static-text',
		id: 'info',
		label: 'Note:',
		value: `The U command is used to update Template data of a single Template in a preexisting Template Data Message.`,
	},
	updateCurrentTemplateInfo: {
		type: 'static-text',
		id: 'info',
		label: 'Note:',
		value: `Although the Lyric interface allows the operator to assign the same value to multiple templates using the Number control, this should be avoided. Assigning the same numerical designation to multiple templates will cause the U/* command not to work correctly. This condition may occur due to manual alteration of field numbers or Lyric numbering new fields following manual deletion and subsequent addition of template fields.`,
	},
	messagePath: {
		...textField,
		label: 'Message Directory',
		id: 'msgPath',
		tooltip: 'ie. C:\\Data\\Messages',
		default: 'C:\\Data\\Messages',
	},
}
